server:
  port: 8191
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
spring:
  datasource:                                           # 数据源的相关配置
    type: com.alibaba.druid.pool.DruidDataSource         # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/hub-util?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  redis:
    database: 1
    host: 127.0.0.1

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:com/mdx/mapper/*.xml
  typeAliasesPackage: com.mdx.pojo
  type-enums-package: com.mdx.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

